# ===============================
# Banco de Dados Producao (MySQL)
# Variaveis de ambiente
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# Configuracoes do JPA/Hibernate
# ===============================
# Em producao, n usar 'update' para evitar perda de dados.
# 'validate' apenas verifica se a tabela existe de acordo com a entidade.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ===============================
# E-mail (Producao)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true